/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCounter {
        "name": string | undefined;
    }
}
declare global {
    interface HTMLMyCounterElement extends Components.MyCounter, HTMLStencilElement {
    }
    var HTMLMyCounterElement: {
        prototype: HTMLMyCounterElement;
        new (): HTMLMyCounterElement;
    };
    interface HTMLElementTagNameMap {
        "my-counter": HTMLMyCounterElement;
    }
}
declare namespace LocalJSX {
    interface MyCounter {
        "name"?: string | undefined;
    }

    interface MyCounterAttributes {
        "name": string | undefined;
    }

    interface IntrinsicElements {
        "my-counter": Omit<MyCounter, keyof MyCounterAttributes> & { [K in keyof MyCounter & keyof MyCounterAttributes]?: MyCounter[K] } & { [K in keyof MyCounter & keyof MyCounterAttributes as `attr:${K}`]?: MyCounterAttributes[K] } & { [K in keyof MyCounter & keyof MyCounterAttributes as `prop:${K}`]?: MyCounter[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-counter": LocalJSX.IntrinsicElements["my-counter"] & JSXBase.HTMLAttributes<HTMLMyCounterElement>;
        }
    }
}
